// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvtKshAFc0v6A6aS_MDMnG_dPs1lwNKJI',
    appId: '1:769763101232:web:5aff1e845050aacc19fbf5',
    messagingSenderId: '769763101232',
    projectId: 'flag-pic-ac72e',
    authDomain: 'flag-pic-ac72e.firebaseapp.com',
    storageBucket: 'flag-pic-ac72e.firebasestorage.app',
    measurementId: 'G-TWLLG33D1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-2qO6LMwJCgaj5YEva4s_k_kszAidUXY',
    appId: '1:769763101232:android:a4ed96cd1f837d4219fbf5',
    messagingSenderId: '769763101232',
    projectId: 'flag-pic-ac72e',
    storageBucket: 'flag-pic-ac72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dzMzmbCJ1di0z9zauYabrTqUtYXaNYY',
    appId: '1:769763101232:ios:3594b0d30fc22a0c19fbf5',
    messagingSenderId: '769763101232',
    projectId: 'flag-pic-ac72e',
    storageBucket: 'flag-pic-ac72e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dzMzmbCJ1di0z9zauYabrTqUtYXaNYY',
    appId: '1:769763101232:ios:3594b0d30fc22a0c19fbf5',
    messagingSenderId: '769763101232',
    projectId: 'flag-pic-ac72e',
    storageBucket: 'flag-pic-ac72e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvtKshAFc0v6A6aS_MDMnG_dPs1lwNKJI',
    appId: '1:769763101232:web:a8bcaba2e030176919fbf5',
    messagingSenderId: '769763101232',
    projectId: 'flag-pic-ac72e',
    authDomain: 'flag-pic-ac72e.firebaseapp.com',
    storageBucket: 'flag-pic-ac72e.firebasestorage.app',
    measurementId: 'G-WGRP23RBC7',
  );

}