// GENERATED FILE - DO NOT EDIT
// ------------------------------------------------------------
// This file was generated by the FlutterFire CLI.
// ------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgD929sf2u6EIQaCAWYQMSJVFc8iUkhDk',
    appId: '1:519800441504:android:ab4e98e7821827796097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
  );

  /// 🔹 Android

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU9mCnCAtRI9bsBygJuriDAG2gbmpBdgQ',
    appId: '1:519800441504:web:04850f63718b7d8b6097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    authDomain: 'flag-pic-fe78f.firebaseapp.com',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
  );

  /// 🔹 Web (ถ้าไม่ได้ใช้ Web สามารถปล่อยไว้ได้)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAGnvO3fCNmlzH1F0iy7CbnSQBnWo4Oc',
    appId: '1:519800441504:ios:fcb4f6b7b88f3d7f6097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
    iosBundleId: 'com.example.flagPic',
  );

  /// 🔹 iOS (ใส่เมื่อใช้จริง)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAGnvO3fCNmlzH1F0iy7CbnSQBnWo4Oc',
    appId: '1:519800441504:ios:fcb4f6b7b88f3d7f6097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
    iosBundleId: 'com.example.flagPic',
  );

  /// 🔹 macOS (ถ้าไม่ใช้ ปล่อยไว้)

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU9mCnCAtRI9bsBygJuriDAG2gbmpBdgQ',
    appId: '1:519800441504:web:5bcbb6e5cda62a746097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    authDomain: 'flag-pic-fe78f.firebaseapp.com',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
  );

  /// 🔹 Windows (ถ้าไม่ใช้ ปล่อยไว้)
}